# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imageManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageControll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageFileName', models.CharField(max_length=50, verbose_name='Image File Name')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Image Create Time')),
                ('imageUrl', models.CharField(max_length=255)),
                ('imageFile', models.ImageField(blank=True, upload_to=imageManagement.models.setImageSaveLocation)),
                ('imageFormat', models.CharField(max_length=10, verbose_name='Image Format')),
                ('imageSize', models.PositiveIntegerField(verbose_name='Image Size')),
                ('imageHeight', models.PositiveIntegerField(verbose_name='Image Height')),
                ('imageWidth', models.PositiveIntegerField(verbose_name='Image Width')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='Note')),
                ('isTraining', models.PositiveIntegerField(verbose_name='image Type')),
            ],
        ),
        migrations.CreateModel(
            name='Model_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100, verbose_name='Model Name')),
                ('modelRoute', models.CharField(max_length=1000, verbose_name='Model Route')),
                ('modelNote', models.CharField(max_length=1000, null=True, verbose_name='Model Note')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=30, verbose_name='Topic Name')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='Topic Create Time')),
                ('trainTimes', models.PositiveIntegerField(default=0, verbose_name='Training Time')),
                ('lastUpdateTime', models.DateTimeField(auto_now=True, null=True, verbose_name='Topic Last Update Time')),
                ('note', models.CharField(max_length=100, null=True, verbose_name='Note')),
            ],
        ),
        migrations.AddField(
            model_name='model_topic',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageManagement.ModelObject'),
        ),
        migrations.AddField(
            model_name='model_topic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageManagement.Topic'),
        ),
        migrations.AddField(
            model_name='imagecontroll',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageManagement.Topic'),
        ),
    ]
