# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-16 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelobject',
            name='modelTextRoute',
            field=models.CharField(max_length=1000, null=True, verbose_name='Model Text Route'),
        ),
        migrations.AddField(
            model_name='modelobject',
            name='modelType',
            field=models.CharField(default='retrain', max_length=1000, null=True, verbose_name='Model type'),
        ),
        migrations.AlterField(
            model_name='modelobject',
            name='modelNote',
            field=models.CharField(max_length=1000, null=True, verbose_name='Model Node'),
        ),
    ]
