# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageManagement', '0002_auto_20161116_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workID', models.CharField(max_length=100, verbose_name='Work ID')),
                ('workStatus', models.CharField(max_length=100, verbose_name='Work Status')),
                ('workBeginTime', models.DateTimeField(auto_now_add=True, verbose_name='Work Begin Time')),
            ],
        ),
    ]
